"""Load instrument NetCDF files and interpolate at arbitrary timestamps.

Provides per-radial ship data (heading, speed, pitch, roll, wind) by
interpolating high-frequency instrument time series onto radar beam timestamps.

Instrument files are generated by the ``revelle`` CLI and follow CF-1.13
conventions with a ``time`` coordinate in datetime64[ns].

Memory model: On first use, the NetCDF data is extracted, NaN-filtered, and
saved as compact ``.npy`` files in a ``_ship_data_cache/`` subdirectory.
All subsequent loads (including across 16+ worker processes) use
``np.load(..., mmap_mode='r')`` so the OS kernel shares the same physical
pages across all processes.  Total footprint: ~214 MB once, regardless of
worker count.
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np

__all__ = ["ShipData"]

logger = logging.getLogger(__name__)

_CACHE_DIR_NAME = "_ship_data_cache"
_CACHE_MARKER = ".complete"


class ShipData:
    """Load instrument NetCDF files and interpolate at arbitrary timestamps.

    Each source maps an output variable name to a NetCDF filename, the variable
    name inside that file, and whether interpolation should use angular wrapping
    (``period=360`` for heading/direction variables).

    On construction the class checks for a ``.npy`` cache directory.  If the
    cache is missing or stale (source NetCDFs are newer), it rebuilds from the
    NetCDFs.  Worker processes then memory-map the cache files read-only.
    """

    # Maps output variable name -> (filename, nc_variable_name, is_angular)
    _SOURCES: dict[str, tuple[str, str, bool]] = {
        "latitude": ("gps_abxtwo.nc", "latitude", False),
        "longitude": ("gps_abxtwo.nc", "longitude", False),
        "heading": ("gyro_sperry.nc", "heading", True),
        "ship_speed": ("gps_abxtwo.nc", "sog", False),
        "pitch": ("mru_phins.nc", "pitch", False),
        "roll": ("mru_phins.nc", "roll", False),
        "wind_speed": ("wind_bridge.nc", "relative_wind_speed", False),
        "wind_direction": ("wind_bridge.nc", "relative_wind_direction", True),
    }

    def __init__(self, data_dir: Path) -> None:
        """Load all available instrument data via memory-mapped cache.

        On first call (or when source NetCDFs change), builds ``.npy`` cache
        files.  Subsequent calls memory-map the existing cache.

        Args:
            data_dir: Directory containing instrument NetCDF files.
        """
        self._data_dir = Path(data_dir)
        self._cache_dir = self._data_dir / _CACHE_DIR_NAME
        self._data: dict[str, tuple[np.ndarray, np.ndarray, bool]] = {}
        # _data[variable] = (time_seconds, values, is_angular)

        if not self._cache_valid():
            self._build_cache()
        self._load_cache()

    # ------------------------------------------------------------------
    # Cache management
    # ------------------------------------------------------------------

    def _cache_valid(self) -> bool:
        """Check if the .npy cache exists and is newer than all source NetCDFs."""
        marker = self._cache_dir / _CACHE_MARKER
        if not marker.exists():
            return False
        marker_mtime = marker.stat().st_mtime
        for _var, (filename, _nc_var, _angular) in self._SOURCES.items():
            src = self._data_dir / filename
            if src.exists() and src.stat().st_mtime > marker_mtime:
                return False
        return True

    def _build_cache(self) -> None:
        """Extract data from NetCDFs, filter NaNs, and save as .npy files."""
        import xarray as xr

        self._cache_dir.mkdir(exist_ok=True)

        # Remove stale marker so concurrent workers won't see a partial cache
        marker = self._cache_dir / _CACHE_MARKER
        if marker.exists():
            marker.unlink()

        # Group by filename so we only open each file once
        file_vars: dict[str, list[str]] = {}
        for var, (filename, _nc_var, _angular) in self._SOURCES.items():
            file_vars.setdefault(filename, []).append(var)

        for filename, var_names in file_vars.items():
            filepath = self._data_dir / filename
            if not filepath.exists():
                logger.warning("Instrument file not found: %s", filepath)
                continue

            try:
                ds = xr.open_dataset(filepath)
            except Exception:
                logger.warning("Failed to open %s", filepath, exc_info=True)
                continue

            try:
                # Convert time to float64 epoch seconds
                time_ns = ds["time"].values.astype("datetime64[ns]").astype(np.int64)
                time_s = (time_ns / 1e9).astype(np.float64)

                for var in var_names:
                    _filename, nc_var, _is_angular = self._SOURCES[var]
                    if nc_var not in ds:
                        logger.warning("Variable '%s' not found in %s", nc_var, filepath)
                        continue

                    values = ds[nc_var].values.astype(np.float64)

                    # Drop NaN entries so np.interp only uses valid data
                    valid = np.isfinite(values)
                    if not np.any(valid):
                        logger.warning("No valid data for '%s' in %s", nc_var, filepath)
                        continue

                    np.save(self._cache_dir / f"{var}_time.npy", time_s[valid])
                    np.save(self._cache_dir / f"{var}_values.npy", values[valid])
                    logger.info(
                        "Cached %s: %d records from %s",
                        var,
                        int(np.sum(valid)),
                        filepath.name,
                    )
            finally:
                ds.close()

        # Write marker last — signals that all .npy files are complete
        marker.touch()

    def _load_cache(self) -> None:
        """Memory-map cached .npy files (read-only)."""
        for var, (_filename, _nc_var, is_angular) in self._SOURCES.items():
            time_path = self._cache_dir / f"{var}_time.npy"
            values_path = self._cache_dir / f"{var}_values.npy"
            if not (time_path.exists() and values_path.exists()):
                continue

            time_s = np.load(time_path, mmap_mode="r")
            values = np.load(values_path, mmap_mode="r")
            self._data[var] = (time_s, values, is_angular)
            logger.info("Mapped %s: %d records", var, len(values))

    # ------------------------------------------------------------------
    # Interpolation
    # ------------------------------------------------------------------

    def interpolate(self, times: np.ndarray, variable: str) -> np.ndarray | None:
        """Interpolate a variable at the given timestamps.

        Args:
            times: Array of datetime64[ns] timestamps.
            variable: Variable name (one of :attr:`available_variables`).

        Returns:
            Interpolated values as float64 array, or ``None`` if the source
            data is unavailable.  Angular variables use sin/cos decomposition
            to handle 0/360 wrap-around correctly.
        """
        if variable not in self._data:
            return None

        time_s, values, is_angular = self._data[variable]

        # Convert input times to float64 epoch seconds
        query_s = times.astype("datetime64[ns]").astype(np.int64) / 1e9

        if is_angular:
            # Decompose into sin/cos, interpolate each linearly, then
            # reconstruct with arctan2.  np.interp's ``period`` parameter
            # makes the *x*-coordinates periodic (not the y-values), so it
            # cannot be used for angular y-value interpolation.
            rad = np.deg2rad(values)
            sin_interp = np.interp(query_s, time_s, np.sin(rad))
            cos_interp = np.interp(query_s, time_s, np.cos(rad))
            return np.rad2deg(np.arctan2(sin_interp, cos_interp)) % 360
        return np.interp(query_s, time_s, values)

    @property
    def available_variables(self) -> list[str]:
        """Return list of variables that were successfully loaded."""
        return list(self._data.keys())

    def __repr__(self) -> str:
        return f"<ShipData variables={self.available_variables}>"
